name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
#      - uses: finnp/create-file-action@master
#        env:
#          FILE_NAME: config.toml
#          FILE_DATA: "OPENAI_API_KEY = ${{ secrets.OPENAI_API_KEY }}\nDEBUG = true"
      - name: Create config.toml
        run: |
          echo "OPENAI_API_KEY = 'dummy value'" > config.toml
          echo "DEBUG = true" >> config.toml
      - name: pre test
        run: | 
          cat config.toml
      - name: Test
        uses: onichandame/python-test-action@master
